export const CREATE_USER_STARTED = "CREATE_USER_STARTED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const FETCH_USER_STARTED = "FETCH_USER_STARTED";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_ALL_USERS_STARTED = "FETCH_ALL_USERS_STARTED";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const DELETE_STARTED = "DELETE_STARTED";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const BLOCK_STARTED = "BLOCK_STARTED";
export const BLOCK_SUCCESS = "BLOCK_SUCCESS";
export const BLOCK_FAILURE = "BLOCK_FAILURE";

export const UNBLOCK_STARTED = "UNBLOCK_STARTED";
export const UNBLOCK_SUCCESS = "UNBLOCK_SUCCESS";
export const UNBLOCK_FAILURE = "UNBLOCK_FAILURE";

export const USER_BLOCKED = "USER_BLOCKED"; 

export const LOGOUT = "LOGOUT";
